services:
  frontend:
    build:
      context: frontend
    ports:
      - 5173:80
  backend:
    build:
      context: backend
    ports:
      - 8888:8888
  mailslurper:
    image: ghcr.io/fulsep/mailslurper #https://github.com/fulsep/mailslurper.git
    ports:
      - 2500:2500
      - 8080:8080
      - 8085:8085
    volumes:
      - ./mailslurper.json:/opt/mailslurper/config.json:ro
