services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=1
    volumes:
      - ./base.sql:/docker-entrypoint-initdb.d/base.sql:ro
    ports:
      - 5432:5432
  backend:
    image: golang
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - 8888:8888
    command:
      - /bin/sh
      - -c
      - go mod download && go install github.com/zzwx/fresh@latest && fresh
  frontend:
    image: node:lts-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - 5173:5173
    command:
      - /bin/sh
      - -c
      - npm install && npm run dev -- --host
  mailslurp:
    build: https://github.com/fulsep/mailslurper.git
    ports:
      - 2500:2500
      - 8080:8080
      - 8085:8085
    volumes:
      - ./mailslurper.json:/opt/mailslurper/config.json:ro
